package ru.ikrom.demo_ide_platform.ui.theme

import androidx.compose.ui.unit.dp

//PADDINGS
val PADDING_MAIN = 14.dp
val PADDING_STANDARD = 14.dp
val PADDING_EXTRA_SMALL = 4.dp
val PADDING_SMALL = 8.dp

//PADDING BETWEEN
val PADDING_BETWEEN_LARGE = 16.dp
val PADDING_BETWEEN_EXTRA_SMALL = 4.dp
val PADDING_BETWEEN_SMALL = 8.dp
val PADDING_BETWEEN_MEDIUM = 16.dp
val PADDING_BETWEEN_MEDIUM_PLUS = 18.dp

//ELEVATIONS
val CARD_ELEVATION = 4.dp

//SIZE
val ICON_MEDIUM = 24.dp
val ICON_SMALL_PLUS = 16.dp

//CORNERS
val RADIUS_CHIP_CORNER = 8.dp